Discussion about arrays

In physics and mathematics, a vector is an element of a vector space
which we can represent as
$$\begin{gather}
\tag{2D}
\mathbf{a} = (a_1, a_2) \in \mathbb{R}^2 \\
\tag{3D}
\mathbf{a} = (a_1, a_2, a_3) \in \mathbb{R}^3
\end{gather}$$
where $a_i \in \mathbb{R}$.

However, in linear algebra a vector is typically differentiated by orientation.
$$\begin{gather}
  \mathbf{a} 
    = \begin{bmatrix}a_1 \\ a_2 \\ a_3 \end{bmatrix} \\
  \mathbf{a}^{\mathsf{T}}
    = \begin{bmatrix} a_1 & a_2 & a_3 \end{bmatrix}
\end{gather}$$
which is why more formal presentation of vectors typically define vectors like
$$
  \mathbf{a} = \begin{bmatrix} a_1 & a_2 & a_3 \end{bmatrix}^\mathsf{T}
$$

This difference is important because we can have something like
$$\begin{gather}
  \mathbf{x}
  = \begin{bmatrix}
    x_1 & x_2 & x_3
  \end{bmatrix}^T 
  \\
  A = \begin{bmatrix} 
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33}
  \end{bmatrix}
\end{gather}$$
which means that
$$
  \mathbf{x}^T A \mathbf{x}
$$
The following code block how 

In [26]:
a1, a2, a3 = 1, 2, 3
a_2D = np.array([1.0, 2.0])
print(f"a_2D:{a_2D}")
print(f"a_2D.shape:{a_2D.shape}")
print("a_2D as a column vector")
print(np.reshape(a_2D, shape=(2,1)))
print(a_2D.reshape(2,1))
print("a_2D as a row vector")
print(np.reshape(a_2D, shape=(1,2)))



a_2D:[1. 2.]
a_2D.shape:(2,)
a_2D as a column vector
[[1.]
 [2.]]
[[1.]
 [2.]]
a_2D as a row vector
[[1. 2.]]


In [25]:
a_3D = np.array([1.0, 2.0, 3.0])
print(f"a_3D:{a_3D}")
print(f"a_3D.shape:{a_3D.shape}")

print(f"a_3D: as a column vector")
print(a_3D.reshape(3,1))
print(f"a_3D: as a row vector")
print(a_3D.reshape(1,3))

a_3D:[1. 2. 3.]
a_3D.shape:(3,)
a_3D: as a column vector
[[1.]
 [2.]
 [3.]]
a_3D: as a row vector
[[1. 2. 3.]]


In [ ]:
import numpy as np
from dataclasses import dataclass
Array3D = np.ndarray
Array2D = np.ndarray

def is_Array2D(r: np.ndarray) -> bool:
    try:
        np.asarray(r, dtype=float).reshape(2,)
        return True
    except Exception:
        return False

def to_Array2D(r: np.ndarray) -> bool:
    try:
        return np.asarray(r, dtype=float).reshape(2,)
    except Exception as e:
        raise e

def is_Array3D(r: np.ndarray) -> bool:
    try:
        np.asarray(x, dtype=float).reshape(3,)
        return True
    except Exception:
        return False

def to_Array2D(r: np.ndarray) -> bool:
    try:
        return np.asarray(r, dtype=float).reshape(3,)
    except Exception as e:
        raise e


@dataclass(frozen=True, slots=True)
class DirectLattice():
    a1: np.ndarray
    a2: np.ndarray
    a3: np.ndarray

    def __post_init__(self):
      a1 = np.asarray(self.a1, dtype=float).reshape(3,)
      a2 = np.asarray(self.a2, dtype=float).reshape(3,)
      a3 = np.asarray(self.a3, dtype=float).reshape(3,)

      #copy into the frozen dataclass safely
      object.__setattr__(self, "a1", a1.copy())
      object.__setattr__(self, "a2", a2.copy())
      object.__setattr__(self, "a3", a3.copy())

    @staticmethod
    from_A(A: np.ndarray) -> "DirectLattice":
        return DirectLattice(
            a1 = A[0,:]
            a2 = A[1,:]
            a3 = A[2,:]
        )
  
      @property
      def A(self) -> np.ndarray:
          """
          Column matrix A = [a1 a2 a3], so that R = A @ n for integer vector n.
          Shape: (3, 3).
          """
          return np.column_stack([a1, a2, a3])

    def generate(self,
        nx_min: int, nx_max: int,
        ny_min: int, ny_max: int,
        nz_min: int, nz_max: int,
        r: np.ndarray = np.array([0,0,0]),
        *,
        endpoints: bool = False
    ) -> np.ndarray:
        # local variables references from class variables
        a1 = self.a1
        a2 = self.a2
        a3 = self.a3

        # change loop behavior depending on desired endpoints
        ix_max = nx_max + 1 if endpoints else nx_max
        iy_max = ny_max + 1 if endpoints else ny_max
        iz_max = nz_max + 1 if endpoints else n_zmax

        R_array = []
        for i in range(nx_min, ix_max):
            for j in range(ny_min, iy_max):
                for k in range(nz_min, iz_max):
                    R = r + i*a1 + j*a2 + k*a3
                    points.append(R)
        return np.asarray(points)

    @property
    def volume(self):
        a1 = self.a1
        a2 = self.a2
        a3 = self.a3
        return abs(np.dot(a1, np.cross(a2, a3)))


In [32]:
lattice = DirectLattice(
  a1 = np.array([1,0,0]),
  a2 = np.array([0,1,0]),
  a3 = np.array([0,0,1]),
)
print(lattice.a1)
print(lattice.a2)
print(lattice.a3)

[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]
